[theme]
primaryColor = "#00F2FE"
backgroundColor = "#0B0E14"
secondaryBackgroundColor = "#141A24"
textColor = "#F1F5F9"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
